# sprig-config-module/config/application-dev.yml
server:
  port: 9090
imports:
  - features.yml
  - override.yml
secrets:
  username: ENC(gAAAAABokVDE6uM8TItupVCEB9URRjbKzxO5bddjHPPBG_9NGjinUdhq3P0sLYFQ76gRrt87Yy3haINdh2_NrO7KobeKokz37A==)
  password: ENC(gAAAAABokVDE3fwikJO6YqTStG4xnh5cPjWNAT3JXw0zB-HDtdqCCRGvNBNogl2yVQDedyvfffc44e2guTs8JHZpD7sBaOqEmQ==)
  apiKey: ENC(gAAAAABokVDEPTHqVtIzELGMtFN89vAcLZcsd-B094VA04b91N8byC5hyZdZKlleq_NqVlO2z1Kke3yQm0nBGvNPG8tjYbKfpQ==)


