server:
  port: 9090
imports:
  - features.yml
  - override.yml
secrets:
  username: ENC(gAAAAABozbYdq8YJdyaCm2FYqsaeOpQHMIfoeCd5d1H2zJ_vQxYWHsZ6LyxGyawksHTIhSDJ5cfQ_3_nH006scSAzjuoABR-zw==)
  password: ENC(gAAAAABozbYqgKBXf_7V5vZ0UC8R9RF6q_ubFW6w5TEw0Fl6ziS7Sbqv-cLB2CTvsTXX6pNJ3uTnmxoqLPtZNF792TZDCpFaOQ==)
  apiKey: ENC(gAAAAABozbZBYbIXjqPvK01-ke7TIqjWLe7chnwUNIYWVQ3bU3Ax6Rx1ZCLKZZO8kaiteJLY1KjUzcgZvIaqmhHZxapbLQNzbwHjQ03UNiCRHMekqzpYB7Lj7V9qkhCFTSmAZhESYGi6)



